FROM eclipse-mosquitto:2.0.18-openssl

COPY src/docker/mqtt/mosquitto.conf /mosquitto/config/mosquitto.conf

COPY src/docker/mqtt/acl_file /acl_file

RUN chown mosquitto:mosquitto /acl_file

RUN chmod 600 /acl_file

COPY src/docker/mqtt/start.sh /start.sh

CMD sh /start.sh
