export const USER_ABI = {
  address: "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74",
  name: "user",
  friends: [
    "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::market",
  ],
  exposed_functions: [
    {
      name: "cancel_order_internal",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address", "u64", "u64", "bool", "u64", "u64", "u64", "u128"],
      return: ["u128"],
    },
    {
      name: "change_order_size_internal",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "address",
        "u64",
        "u64",
        "bool",
        "u64",
        "u64",
        "u64",
        "u64",
        "u128",
      ],
      return: [],
    },
    {
      name: "create_cancel_order_event",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["u64", "u128", "address", "u64", "u8"],
      return: [
        "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::CancelOrderEvent",
      ],
    },
    {
      name: "create_change_order_size_event",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["u64", "u128", "address", "u64", "bool", "u64"],
      return: [
        "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::ChangeOrderSizeEvent",
      ],
    },
    {
      name: "create_fill_event",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "u64",
        "u64",
        "u64",
        "bool",
        "address",
        "u64",
        "u128",
        "address",
        "u64",
        "u128",
        "u64",
        "u64",
      ],
      return: [
        "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::FillEvent",
      ],
    },
    {
      name: "create_place_limit_order_event",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "u64",
        "address",
        "u64",
        "address",
        "bool",
        "u64",
        "u64",
        "u8",
        "u8",
        "u64",
        "u128",
      ],
      return: [
        "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::PlaceLimitOrderEvent",
      ],
    },
    {
      name: "create_place_market_order_event",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["u64", "address", "u64", "address", "bool", "u64", "u8", "u128"],
      return: [
        "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::PlaceMarketOrderEvent",
      ],
    },
    {
      name: "deposit_assets_internal",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [
        {
          constraints: [],
        },
        {
          constraints: [],
        },
      ],
      params: [
        "address",
        "u64",
        "u64",
        "u64",
        "0x1::option::Option<0x1::coin::Coin<T0>>",
        "0x1::coin::Coin<T1>",
        "u64",
      ],
      return: [],
    },
    {
      name: "deposit_coins",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [
        {
          constraints: [],
        },
      ],
      params: ["address", "u64", "u64", "0x1::coin::Coin<T0>"],
      return: [],
    },
    {
      name: "deposit_from_coinstore",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [
        {
          constraints: [],
        },
      ],
      params: ["&signer", "u64", "u64", "u64"],
      return: [],
    },
    {
      name: "deposit_generic_asset",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "address",
        "u64",
        "u64",
        "u64",
        "&0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::registry::UnderwriterCapability",
      ],
      return: [],
    },
    {
      name: "emit_cancel_order_event",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::CancelOrderEvent",
      ],
      return: [],
    },
    {
      name: "emit_change_order_size_event",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::ChangeOrderSizeEvent",
      ],
      return: [],
    },
    {
      name: "emit_fill_event_for_maker",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::FillEvent",
      ],
      return: [],
    },
    {
      name: "emit_fill_event_for_maker_and_taker",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::FillEvent",
      ],
      return: [],
    },
    {
      name: "emit_place_limit_order_event",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::PlaceLimitOrderEvent",
      ],
      return: [],
    },
    {
      name: "emit_place_market_order_event",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::PlaceMarketOrderEvent",
      ],
      return: [],
    },
    {
      name: "fill_order_internal",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [
        {
          constraints: [],
        },
        {
          constraints: [],
        },
      ],
      params: [
        "address",
        "u64",
        "u64",
        "bool",
        "u64",
        "u64",
        "u64",
        "bool",
        "0x1::option::Option<0x1::coin::Coin<T0>>",
        "0x1::coin::Coin<T1>",
        "u64",
        "u64",
      ],
      return: [
        "0x1::option::Option<0x1::coin::Coin<T0>>",
        "0x1::coin::Coin<T1>",
        "u128",
      ],
    },
    {
      name: "get_ASK",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["bool"],
    },
    {
      name: "get_BID",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["bool"],
    },
    {
      name: "get_CANCEL_REASON_EVICTION",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u8"],
    },
    {
      name: "get_CANCEL_REASON_IMMEDIATE_OR_CANCEL",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u8"],
    },
    {
      name: "get_CANCEL_REASON_MANUAL_CANCEL",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u8"],
    },
    {
      name: "get_CANCEL_REASON_MAX_QUOTE_TRADED",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u8"],
    },
    {
      name: "get_CANCEL_REASON_NOT_ENOUGH_LIQUIDITY",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u8"],
    },
    {
      name: "get_CANCEL_REASON_SELF_MATCH_MAKER",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u8"],
    },
    {
      name: "get_CANCEL_REASON_SELF_MATCH_TAKER",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u8"],
    },
    {
      name: "get_CANCEL_REASON_TOO_SMALL_AFTER_MATCHING",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u8"],
    },
    {
      name: "get_NO_CUSTODIAN",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["u64"],
    },
    {
      name: "get_active_market_order_ids_internal",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address", "u64", "u64", "bool"],
      return: ["vector<u128>"],
    },
    {
      name: "get_all_market_account_ids_for_market_id",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "u64"],
      return: ["vector<u128>"],
    },
    {
      name: "get_all_market_account_ids_for_user",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["vector<u128>"],
    },
    {
      name: "get_asset_counts_custodian",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "address",
        "u64",
        "&0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::registry::CustodianCapability",
      ],
      return: ["u64", "u64", "u64", "u64", "u64", "u64"],
    },
    {
      name: "get_asset_counts_internal",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address", "u64", "u64"],
      return: ["u64", "u64", "u64", "u64", "u64", "u64"],
    },
    {
      name: "get_asset_counts_user",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64"],
      return: ["u64", "u64", "u64", "u64", "u64", "u64"],
    },
    {
      name: "get_custodian_id",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["u128"],
      return: ["u64"],
    },
    {
      name: "get_fill_event_taker_order_id",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "&0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::FillEvent",
      ],
      return: ["u128"],
    },
    {
      name: "get_market_account_id",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["u64", "u64"],
      return: ["u128"],
    },
    {
      name: "get_market_account_market_info_custodian",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "address",
        "u64",
        "&0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::registry::CustodianCapability",
      ],
      return: [
        "0x1::type_info::TypeInfo",
        "0x1::string::String",
        "0x1::type_info::TypeInfo",
        "u64",
        "u64",
        "u64",
        "u64",
      ],
    },
    {
      name: "get_market_account_market_info_user",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64"],
      return: [
        "0x1::type_info::TypeInfo",
        "0x1::string::String",
        "0x1::type_info::TypeInfo",
        "u64",
        "u64",
        "u64",
        "u64",
      ],
    },
    {
      name: "get_market_id",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["u128"],
      return: ["u64"],
    },
    {
      name: "get_next_order_access_key_internal",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address", "u64", "u64", "bool"],
      return: ["u64"],
    },
    {
      name: "get_open_order_id_internal",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address", "u64", "u64", "bool", "u64"],
      return: ["0x1::option::Option<u128>"],
    },
    {
      name: "has_market_account",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "u64", "u64"],
      return: ["bool"],
    },
    {
      name: "has_market_account_by_market_account_id",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "u128"],
      return: ["bool"],
    },
    {
      name: "has_market_account_by_market_id",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "u64"],
      return: ["bool"],
    },
    {
      name: "init_market_event_handles_if_missing",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64", "u64"],
      return: [],
    },
    {
      name: "place_order_internal",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address", "u64", "u64", "bool", "u64", "u64", "u128", "u64"],
      return: [],
    },
    {
      name: "register_market_account",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [
        {
          constraints: [],
        },
        {
          constraints: [],
        },
      ],
      params: ["&signer", "u64", "u64"],
      return: [],
    },
    {
      name: "register_market_account_generic_base",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [
        {
          constraints: [],
        },
      ],
      params: ["&signer", "u64", "u64"],
      return: [],
    },
    {
      name: "set_fill_event_taker_order_id",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "&mut 0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::FillEvent",
        "u128",
      ],
      return: [],
    },
    {
      name: "withdraw_assets_internal",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [
        {
          constraints: [],
        },
        {
          constraints: [],
        },
      ],
      params: ["address", "u64", "u64", "u64", "u64", "u64"],
      return: [
        "0x1::option::Option<0x1::coin::Coin<T0>>",
        "0x1::coin::Coin<T1>",
      ],
    },
    {
      name: "withdraw_coins_custodian",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [
        {
          constraints: [],
        },
      ],
      params: [
        "address",
        "u64",
        "u64",
        "&0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::registry::CustodianCapability",
      ],
      return: ["0x1::coin::Coin<T0>"],
    },
    {
      name: "withdraw_coins_user",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [
        {
          constraints: [],
        },
      ],
      params: ["&signer", "u64", "u64"],
      return: ["0x1::coin::Coin<T0>"],
    },
    {
      name: "withdraw_generic_asset_custodian",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "address",
        "u64",
        "u64",
        "&0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::registry::CustodianCapability",
        "&0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::registry::UnderwriterCapability",
      ],
      return: [],
    },
    {
      name: "withdraw_generic_asset_user",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "u64",
        "u64",
        "&0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::registry::UnderwriterCapability",
      ],
      return: [],
    },
    {
      name: "withdraw_to_coinstore",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [
        {
          constraints: [],
        },
      ],
      params: ["&signer", "u64", "u64"],
      return: [],
    },
  ],
  structs: [
    {
      name: "CancelOrderEvent",
      is_native: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "market_id",
          type: "u64",
        },
        {
          name: "order_id",
          type: "u128",
        },
        {
          name: "user",
          type: "address",
        },
        {
          name: "custodian_id",
          type: "u64",
        },
        {
          name: "reason",
          type: "u8",
        },
      ],
    },
    {
      name: "ChangeOrderSizeEvent",
      is_native: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "market_id",
          type: "u64",
        },
        {
          name: "order_id",
          type: "u128",
        },
        {
          name: "user",
          type: "address",
        },
        {
          name: "custodian_id",
          type: "u64",
        },
        {
          name: "side",
          type: "bool",
        },
        {
          name: "new_size",
          type: "u64",
        },
      ],
    },
    {
      name: "Collateral",
      is_native: false,
      abilities: ["key"],
      generic_type_params: [
        {
          constraints: [],
        },
      ],
      fields: [
        {
          name: "map",
          type: "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::tablist::Tablist<u128, 0x1::coin::Coin<T0>>",
        },
      ],
    },
    {
      name: "FillEvent",
      is_native: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "market_id",
          type: "u64",
        },
        {
          name: "size",
          type: "u64",
        },
        {
          name: "price",
          type: "u64",
        },
        {
          name: "maker_side",
          type: "bool",
        },
        {
          name: "maker",
          type: "address",
        },
        {
          name: "maker_custodian_id",
          type: "u64",
        },
        {
          name: "maker_order_id",
          type: "u128",
        },
        {
          name: "taker",
          type: "address",
        },
        {
          name: "taker_custodian_id",
          type: "u64",
        },
        {
          name: "taker_order_id",
          type: "u128",
        },
        {
          name: "taker_quote_fees_paid",
          type: "u64",
        },
        {
          name: "sequence_number_for_trade",
          type: "u64",
        },
      ],
    },
    {
      name: "MarketAccount",
      is_native: false,
      abilities: ["store"],
      generic_type_params: [],
      fields: [
        {
          name: "base_type",
          type: "0x1::type_info::TypeInfo",
        },
        {
          name: "base_name_generic",
          type: "0x1::string::String",
        },
        {
          name: "quote_type",
          type: "0x1::type_info::TypeInfo",
        },
        {
          name: "lot_size",
          type: "u64",
        },
        {
          name: "tick_size",
          type: "u64",
        },
        {
          name: "min_size",
          type: "u64",
        },
        {
          name: "underwriter_id",
          type: "u64",
        },
        {
          name: "asks",
          type: "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::tablist::Tablist<u64, 0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::Order>",
        },
        {
          name: "bids",
          type: "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::tablist::Tablist<u64, 0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::Order>",
        },
        {
          name: "asks_stack_top",
          type: "u64",
        },
        {
          name: "bids_stack_top",
          type: "u64",
        },
        {
          name: "base_total",
          type: "u64",
        },
        {
          name: "base_available",
          type: "u64",
        },
        {
          name: "base_ceiling",
          type: "u64",
        },
        {
          name: "quote_total",
          type: "u64",
        },
        {
          name: "quote_available",
          type: "u64",
        },
        {
          name: "quote_ceiling",
          type: "u64",
        },
      ],
    },
    {
      name: "MarketAccountView",
      is_native: false,
      abilities: ["store"],
      generic_type_params: [],
      fields: [
        {
          name: "market_id",
          type: "u64",
        },
        {
          name: "custodian_id",
          type: "u64",
        },
        {
          name: "asks",
          type: "vector<0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::Order>",
        },
        {
          name: "bids",
          type: "vector<0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::Order>",
        },
        {
          name: "base_total",
          type: "u64",
        },
        {
          name: "base_available",
          type: "u64",
        },
        {
          name: "base_ceiling",
          type: "u64",
        },
        {
          name: "quote_total",
          type: "u64",
        },
        {
          name: "quote_available",
          type: "u64",
        },
        {
          name: "quote_ceiling",
          type: "u64",
        },
      ],
    },
    {
      name: "MarketAccounts",
      is_native: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "map",
          type: "0x1::table::Table<u128, 0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::MarketAccount>",
        },
        {
          name: "custodians",
          type: "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::tablist::Tablist<u64, vector<u64>>",
        },
      ],
    },
    {
      name: "MarketEventHandles",
      is_native: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "cancel_order_events",
          type: "0x1::table::Table<u128, 0x1::event::EventHandle<0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::CancelOrderEvent>>",
        },
        {
          name: "change_order_size_events",
          type: "0x1::table::Table<u128, 0x1::event::EventHandle<0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::ChangeOrderSizeEvent>>",
        },
        {
          name: "fill_events",
          type: "0x1::table::Table<u128, 0x1::event::EventHandle<0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::FillEvent>>",
        },
        {
          name: "place_limit_order_events",
          type: "0x1::table::Table<u128, 0x1::event::EventHandle<0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::PlaceLimitOrderEvent>>",
        },
        {
          name: "place_market_order_events",
          type: "0x1::table::Table<u128, 0x1::event::EventHandle<0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74::user::PlaceMarketOrderEvent>>",
        },
      ],
    },
    {
      name: "Order",
      is_native: false,
      abilities: ["store"],
      generic_type_params: [],
      fields: [
        {
          name: "market_order_id",
          type: "u128",
        },
        {
          name: "size",
          type: "u64",
        },
      ],
    },
    {
      name: "PlaceLimitOrderEvent",
      is_native: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "market_id",
          type: "u64",
        },
        {
          name: "user",
          type: "address",
        },
        {
          name: "custodian_id",
          type: "u64",
        },
        {
          name: "integrator",
          type: "address",
        },
        {
          name: "side",
          type: "bool",
        },
        {
          name: "size",
          type: "u64",
        },
        {
          name: "price",
          type: "u64",
        },
        {
          name: "restriction",
          type: "u8",
        },
        {
          name: "self_match_behavior",
          type: "u8",
        },
        {
          name: "remaining_size",
          type: "u64",
        },
        {
          name: "order_id",
          type: "u128",
        },
      ],
    },
    {
      name: "PlaceMarketOrderEvent",
      is_native: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "market_id",
          type: "u64",
        },
        {
          name: "user",
          type: "address",
        },
        {
          name: "custodian_id",
          type: "u64",
        },
        {
          name: "integrator",
          type: "address",
        },
        {
          name: "direction",
          type: "bool",
        },
        {
          name: "size",
          type: "u64",
        },
        {
          name: "self_match_behavior",
          type: "u8",
        },
        {
          name: "order_id",
          type: "u128",
        },
      ],
    },
  ],
} as const;
