FROM postgres:14-bookworm

RUN apt-get update -y \
    && apt-get install -y git make \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/michelp/pgjwt

WORKDIR ./pgjwt

RUN make install

RUN apt autoremove -y git make

WORKDIR ..

RUN rm -rf ./pgjwt

HEALTHCHECK --interval=5s --timeout=3s \
    CMD pg_isready -h localhost -p 5432 -U econia || exit 1
